import type { SentMessage } from '@/types/message'

export const sentMessages: SentMessage[] = [
  {
    id: '1',
    nickname: 'devYuna',
    receiver: 'codeBear',
    content: '안녕하세요! 스터디 관련해서 연락드렸어요.',
    sentAt: '2025-08-01 10:23',
  },
  {
    id: '2',
    nickname: 'devYuna',
    receiver: 'frontend99',
    content: '코드 리뷰 감사합니다. 많이 배웠어요!',
    sentAt: '2025-08-01 15:42',
  },
  {
    id: '3',
    nickname: 'devYuna',
    receiver: 'JSJun',
    content: '다음 회의는 금요일 2시로 하겠습니다.',
    sentAt: '2025-08-02 09:10',
  },
  {
    id: '4',
    nickname: 'devYuna',
    receiver: 'ReactRina',
    content: '폴더 구조 공유해주실 수 있나요?',
    sentAt: '2025-08-02 13:55',
  },
  {
    id: '5',
    nickname: 'devYuna',
    receiver: 'KimJS',
    content: '라이브러리 버전 맞췄습니다. 확인 부탁드려요.',
    sentAt: '2025-08-03 08:44',
  },
  {
    id: '6',
    nickname: 'devYuna',
    receiver: 'algorhythm',
    content: '그 부분 다시 설명해주실 수 있나요?',
    sentAt: '2025-08-03 12:20',
  },
  {
    id: '7',
    nickname: 'devYuna',
    receiver: 'dataLover',
    content: '다음엔 GraphQL로 구현해보려고 해요.',
    sentAt: '2025-08-03 17:30',
  },
  {
    id: '8',
    nickname: 'devYuna',
    receiver: 'weekendDev',
    content: '스터디 일정 다시 조율할게요!',
    sentAt: '2025-08-04 08:05',
  },
  {
    id: '9',
    nickname: 'devYuna',
    receiver: 'refactorKing',
    content: '코드 리팩토링한 부분 봐주세요.',
    sentAt: '2025-08-04 10:45',
  },
  {
    id: '10',
    nickname: 'devYuna',
    receiver: 'testUser123',
    content: '테스트 케이스 몇 개 추가했습니다.',
    sentAt: '2025-08-04 13:14',
  },
  {
    id: '11',
    nickname: 'devYuna',
    receiver: 'UXSarah',
    content: '피드백 감사합니다. 반영했어요!',
    sentAt: '2025-08-04 14:20',
  },
  {
    id: '12',
    nickname: 'devYuna',
    receiver: 'TeamLeadJo',
    content: 'PR 리뷰 부탁드립니다!',
    sentAt: '2025-08-04 14:38',
  },
  {
    id: '13',
    nickname: 'devYuna',
    receiver: 'studyMate1',
    content: '이번 주 과제는 언제까지였죠?',
    sentAt: '2025-08-04 14:40',
  },
  {
    id: '14',
    nickname: 'devYuna',
    receiver: 'gitMaster',
    content: 'merge conflict 해결했습니다.',
    sentAt: '2025-08-04 14:41',
  },
  {
    id: '15',
    nickname: 'devYuna',
    receiver: 'planDev',
    content: '다음 프로젝트 계획 공유해드릴게요.',
    sentAt: '2025-08-04 14:42',
  },
  {
    id: '16',
    nickname: 'devYuna',
    receiver: 'noteKing',
    content: '정리해주신 문서 정말 유용했어요!',
    sentAt: '2025-08-04 14:44',
  },
  {
    id: '17',
    nickname: 'devYuna',
    receiver: 'NextTime',
    content: 'Next.js 관련해서 궁금한 게 있어요.',
    sentAt: '2025-08-04 14:46',
  },
  {
    id: '18',
    nickname: 'devYuna',
    receiver: 'codeSmell',
    content: '리팩토링 제안 감사해요. 적용했어요!',
    sentAt: '2025-08-04 14:47',
  },
  {
    id: '19',
    nickname: 'devYuna',
    receiver: 'dailyCommit',
    content: '커밋 로그 형식 통일했어요.',
    sentAt: '2025-08-04 14:48',
  },
  {
    id: '20',
    nickname: 'devYuna',
    receiver: 'coffeeTime',
    content: '쉬는 시간에 같이 커피 한 잔 어때요?',
    sentAt: '2025-08-04 14:49',
  },
]
